# /k8s/advanced-storage-secrets.yaml
# Advanced storage secrets for S3, OpenSearch, and other services
apiVersion: v1
kind: Secret
metadata:
  name: storage-credentials
  labels:
    app: contact-api
    storage-type: credentials
type: Opaque
data:
  # Base64 encoded credentials (replace with actual values)
  aws-access-key-id: QUtJQUlPU0ZPRE5UREVSR0tB  # Replace with actual base64 encoded access key
  aws-secret-access-key: d0phbHJYVXRuRkVNc0Z3REdQV2F3V2J0V1F3  # Replace with actual base64 encoded secret key
  opensearch-username: YWRtaW4=  # admin
  opensearch-password: QWRtaW4xMjMh  # Admin123!
  opensearch-endpoint: aHR0cHM6Ly9zZWFyY2gtcmVhbGlzdGljLWRlbW8tcHJldGFtYW5lLXVzLWVhc3QtMS5lc2EuYW1hem9uYXdzLmNvbQ==  # Replace with actual endpoint
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-bucket-info
  labels:
    app: contact-api
    storage-type: s3
type: Opaque
data:
  data-bucket: cmVhbGlzdGljLWRlbW8tcHJldGFtYW5lLWRhdGEtYWJjZGVm  # Replace with actual bucket name
  index-bucket: cmVhbGlzdGljLWRlbW8tcHJldGFtYW5lLWluZGV4LWFiY2RlZg==  # Replace with actual bucket name
  backup-bucket: cmVhbGlzdGljLWRlbW8tcHJldGFtYW5lLWJhY2t1cC1hYmNkZWY=  # Replace with actual bucket name
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-config
  labels:
    app: contact-api
    storage-type: opensearch
type: Opaque
data:
  endpoint: aHR0cHM6Ly9zZWFyY2gtcmVhbGlzdGljLWRlbW8tcHJldGFtYW5lLXVzLWVhc3QtMS5lc2EuYW1hem9uYXdzLmNvbQ==  # Replace with actual endpoint
  index-name: ZG9jdW1lbnRz  # documents
  username: YWRtaW4=  # admin
  password: QWRtaW4xMjMh  # Admin123!
---
# ConfigMap for storage configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
  labels:
    app: contact-api
    storage-type: config
data:
  # S3 Configuration
  S3_DATA_BUCKET: "realistic-demo-pretamane-data-abcdef"  # Replace with actual bucket name
  S3_INDEX_BUCKET: "realistic-demo-pretamane-index-abcdef"  # Replace with actual bucket name
  S3_BACKUP_BUCKET: "realistic-demo-pretamane-backup-abcdef"  # Replace with actual bucket name
  S3_REGION: "ap-southeast-1"
  
  # OpenSearch Configuration
  OPENSEARCH_ENDPOINT: "https://search-realistic-demo-pretamane-us-east-1.es.amazonaws.com"  # Replace with actual endpoint
  OPENSEARCH_INDEX: "documents"
  OPENSEARCH_USERNAME: "admin"
  
  # EFS Configuration
  EFS_MOUNT_PATH: "/mnt/efs"
  EFS_SHARED_PATH: "/mnt/efs/shared"
  EFS_UPLOADS_PATH: "/mnt/efs/uploads"
  EFS_LOGS_PATH: "/mnt/efs/logs"
  
  # Storage Policies
  STORAGE_RETENTION_DAYS: "30"
  STORAGE_BACKUP_ENABLED: "true"
  STORAGE_ENCRYPTION_ENABLED: "true"
  
  # Indexing Configuration
  INDEX_BATCH_SIZE: "100"
  INDEX_REFRESH_INTERVAL: "30s"
  INDEX_REPLICAS: "1"
  INDEX_SHARDS: "3"
