# /k8s/advanced-storage-secrets.yaml
# Advanced storage secrets for S3, OpenSearch, and other services
# SECURITY WARNING: Replace all hardcoded values with your actual credentials
# Use: kubectl create secret generic storage-credentials --from-literal=aws-access-key-id=YOUR_KEY --from-literal=aws-secret-access-key=YOUR_SECRET
apiVersion: v1
kind: Secret
metadata:
  name: storage-credentials
  labels:
    app: contact-api
    storage-type: credentials
type: Opaque
data:
  # Base64 encoded credentials - REPLACE WITH YOUR ACTUAL VALUES
  # To encode: echo -n "YOUR_ACCESS_KEY" | base64
  # To encode: echo -n "YOUR_SECRET_KEY" | base64
  aws-access-key-id: REPLACE_WITH_YOUR_BASE64_ENCODED_ACCESS_KEY
  aws-secret-access-key: REPLACE_WITH_YOUR_BASE64_ENCODED_SECRET_KEY
  opensearch-username: REPLACE_WITH_YOUR_OPENSEARCH_USERNAME_BASE64
  opensearch-password: REPLACE_WITH_YOUR_OPENSEARCH_PASSWORD_BASE64
  opensearch-endpoint: REPLACE_WITH_YOUR_OPENSEARCH_ENDPOINT_BASE64
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-bucket-info
  labels:
    app: contact-api
    storage-type: s3
type: Opaque
data:
  data-bucket: REPLACE_WITH_YOUR_DATA_BUCKET_NAME_BASE64
  index-bucket: REPLACE_WITH_YOUR_INDEX_BUCKET_NAME_BASE64
  backup-bucket: REPLACE_WITH_YOUR_BACKUP_BUCKET_NAME_BASE64
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-config
  labels:
    app: contact-api
    storage-type: opensearch
type: Opaque
data:
  endpoint: REPLACE_WITH_YOUR_OPENSEARCH_ENDPOINT_BASE64
  index-name: ZG9jdW1lbnRz  # documents (this is safe to keep)
  username: REPLACE_WITH_YOUR_OPENSEARCH_USERNAME_BASE64
  password: REPLACE_WITH_YOUR_OPENSEARCH_PASSWORD_BASE64
---
# ConfigMap for storage configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
  labels:
    app: contact-api
    storage-type: config
data:
  # S3 Configuration - REPLACE WITH YOUR ACTUAL BUCKET NAMES
  S3_DATA_BUCKET: "REPLACE_WITH_YOUR_DATA_BUCKET_NAME"
  S3_INDEX_BUCKET: "REPLACE_WITH_YOUR_INDEX_BUCKET_NAME"
  S3_BACKUP_BUCKET: "REPLACE_WITH_YOUR_BACKUP_BUCKET_NAME"
  S3_REGION: "ap-southeast-1"
  
  # OpenSearch Configuration - REPLACE WITH YOUR ACTUAL ENDPOINT
  OPENSEARCH_ENDPOINT: "REPLACE_WITH_YOUR_OPENSEARCH_ENDPOINT"
  OPENSEARCH_INDEX: "documents"
  OPENSEARCH_USERNAME: "REPLACE_WITH_YOUR_OPENSEARCH_USERNAME"
  
  # EFS Configuration
  EFS_MOUNT_PATH: "/mnt/efs"
  EFS_SHARED_PATH: "/mnt/efs/shared"
  EFS_UPLOADS_PATH: "/mnt/efs/uploads"
  EFS_LOGS_PATH: "/mnt/efs/logs"
  
  # Storage Policies
  STORAGE_RETENTION_DAYS: "30"
  STORAGE_BACKUP_ENABLED: "true"
  STORAGE_ENCRYPTION_ENABLED: "true"
  
  # Indexing Configuration
  INDEX_BATCH_SIZE: "100"
  INDEX_REFRESH_INTERVAL: "30s"
  INDEX_REPLICAS: "1"
  INDEX_SHARDS: "3"
