# /k8s/advanced-efs-pv.yaml
# Advanced EFS Persistent Volume with proper CSI configuration
apiVersion: v1
kind: PersistentVolume
metadata:
  name: advanced-efs-pv
  labels:
    app: contact-api
    storage-type: efs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0075863cfd5b77ae1::fsap-0698cf703fee51337
    volumeAttributes:
      provisioningMode: efs-ap
      fileSystemId: fs-0075863cfd5b77ae1
      accessPointId: fsap-0698cf703fee51337
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: advanced-efs-pvc
  labels:
    app: contact-api
    storage-type: efs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0075863cfd5b77ae1
  accessPointId: fsap-0698cf703fee51337
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
# Additional EFS Storage Classes for different use cases
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc-shared
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0075863cfd5b77ae1  # Replace with actual EFS file system ID
  accessPointId: fsap-0698cf703fee51337  # Replace with actual access point ID
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc-secure
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0075863cfd5b77ae1  # Replace with actual EFS file system ID
  accessPointId: fsap-0698cf703fee51337  # Replace with actual access point ID
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
