# /k8s/aws-credentials-secret.yaml
# Secret for AWS credentials (for RClone sidecar)
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded credentials (replace with actual values)
  # To encode: echo -n "your-access-key" | base64
  access-key-id: ""  # Replace with base64 encoded access key
  secret-access-key: ""  # Replace with base64 encoded secret key
