# /k8s/aws-credentials-secret.yaml
# Secret for AWS credentials (for RClone sidecar)
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded credentials
  access-key-id: "QUtJQVY3WjZRV0pLQUNJUUREN04="
  secret-access-key: "VWRRSzQ5dzIxaDE3RHdSTDcvbDJha2RrQm5MYWkzdXZiaVJXL1FpQg=="
