# /k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-api
  labels:
    app: contact-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-api
  template:
    metadata:
      labels:
        app: contact-api
    spec:
      serviceAccountName: contact-api
      containers:
      - name: contact-api
        image: pretamane/contact-api:latest # ← You'll build & push this later
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: "ap-southeast-1"
        - name: CONTACTS_TABLE
          value: "realistic-demo-pretamane-contact-submissions"
        - name: VISITORS_TABLE
          value: "realistic-demo-pretamane-website-visitors"
        - name: SES_FROM_EMAIL
          value: "thawzin252467@gmail.com"
        - name: SES_TO_EMAIL
          value: "thawzin252467@gmail.com"
        - name: ALLOWED_ORIGIN
          value: "*"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Always