# /k8s/efs-contact-api.yaml
# Optimized EFS configuration using pure dynamic provisioning
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc-contact-api
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0075863cfd5b77ae1
  accessPointId: fsap-0698cf703fee51337
  directoryPerms: "0755"
  uid: "1000"
  gid: "1000"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: advanced-efs-pvc
  labels:
    app: contact-api
    storage-type: efs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc-contact-api
