# /k8s/efs-static-simple.yaml
# Simple static EFS configuration using existing access point
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
  labels:
    app: contact-api
    storage-type: efs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0075863cfd5b77ae1::fsap-0698cf703fee51337
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: advanced-efs-pvc
  labels:
    app: contact-api
    storage-type: efs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: efs-static-pv
