# /k8s/efs-pv.yaml
# EFS Persistent Volume for shared storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-12345678  # Replace with actual EFS file system ID
    volumeAttributes:
      provisioningMode: efs-ap
      fileSystemId: fs-12345678  # Replace with actual EFS file system ID
      directoryPerms: "0755"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-12345678  # Replace with actual EFS file system ID
  directoryPerms: "0755"
reclaimPolicy: Retain
allowVolumeExpansion: true
