# /k8s/init-container-mount.yaml
# Init Container for data mounting and preparation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-api-with-init
  labels:
    app: contact-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-api
  template:
    metadata:
      labels:
        app: contact-api
    spec:
      serviceAccountName: contact-api
      
      # Init Container for data preparation
      initContainers:
      - name: data-prep
        image: alpine:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Initializing data preparation..."
            # Create shared data directory
            mkdir -p /shared-data/uploads
            mkdir -p /shared-data/logs
            mkdir -p /shared-data/config
            
            # Download initial configuration from S3 (simulated)
            echo "Downloading initial configuration..."
            cat > /shared-data/config/app-config.json << EOF
            {
              "version": "1.0.0",
              "features": {
                "fileUpload": true,
                "logging": true,
                "monitoring": true
              },
              "storage": {
                "type": "s3",
                "bucket": "realistic-demo-pretamane-terraform-state"
              }
            }
            EOF
            
            # Create sample data files
            echo "Creating sample data files..."
            echo "Sample log entry $(date)" > /shared-data/logs/app.log
            echo "Sample upload data" > /shared-data/uploads/sample.txt
            
            # Set proper permissions
            chmod -R 755 /shared-data
            
            echo "Data preparation completed!"
        volumeMounts:
        - name: shared-storage
          mountPath: /shared-data
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"

      containers:
      # Main FastAPI Application
      - name: contact-api
        image: python:3.11-slim
        command: ["/bin/bash"]
        args: ["-c", "pip install fastapi uvicorn boto3 pydantic[email] && cp /app/app.py /tmp/app.py && cd /tmp && python app.py"]
        volumeMounts:
        - name: app-config
          mountPath: /app
        - name: shared-storage
          mountPath: /shared-data
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: "ap-southeast-1"
        - name: CONTACTS_TABLE
          value: "realistic-demo-pretamane-contact-submissions"
        - name: VISITORS_TABLE
          value: "realistic-demo-pretamane-website-visitors"
        - name: SES_FROM_EMAIL
          value: "thawzin252467@gmail.com"
        - name: SES_TO_EMAIL
          value: "thawzin252467@gmail.com"
        - name: ALLOWED_ORIGIN
          value: "*"
        - name: SHARED_DATA_PATH
          value: "/shared-data"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20

      volumes:
      - name: app-config
        configMap:
          name: contact-api-config
      - name: shared-storage
        emptyDir:
          sizeLimit: 1Gi
