# Prometheus Datasource Configuration
# Automatically configures Prometheus as a data source for Grafana
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "30s"
      queryTimeout: "300s"
      tlsSkipVerify: true


